### ISSUE TITLE
Support for React 0.13

### ISSUE THREAD

**Issue by mairh** [tomchentw/react-prism#13]
It would be nice if you support both React 0.13 and 0.14 as your peerDependencies. Since React 0.14 is fairly new and not all the projects have upgraded to 0.14.

As of npm 3.0.* peerDependencies are not automatically installed and running `npm install` gives warning in `react-prism` regarding React 0.14

Note: I am using React 0.13.3 in my project.

**Comment by tomchentw** [comment]
Please use v1.x for now https://github.com/tomchentw/react-prism/blob/master/CHANGELOG.md#141-2015-07-01

**Comment by tomchentw** [comment]
Close this if no further update.
