### ISSUE TITLE
Use PureComponent instead of react-addons-pure-render-mixin

### ISSUE THREAD

**Issue by schickling** [tomchentw/react-prism#21]
Please drop the peer dependency on `react-addons-pure-render-mixin` in favour of React's `PureComponent`

**Comment by ZeroCho** [comment]
+1

**Comment by tomchentw** [comment]
PRs are welcomed.

**Comment by ZeroCho** [comment]
@tomchentw I'm working on it

**Comment by ZeroCho** [comment]
@tomchentw #25

**Comment by tomchentw** [comment]
Released [v4.0.0](https://github.com/tomchentw/react-prism/releases/tag/v4.0.0)
