### ISSUE TITLE
custom highlighting style

### ISSUE THREAD

**Issue by kennetpostigo** [tomchentw/react-prism#28]
Is there anyway to change the color of the highlighting? I'm asking because I want it to match the style of the site.

**Comment by tomchentw** [comment]
Could you check the example from http://prismjs.com/? Search `customizing` and you'll get the link:
http://asarosenberg.se/code/extending-and-customizing-prism-syntax-highlighter/

**Comment by kennetpostigo** [comment]
Right and the way to do this is by using: 
```js
// 1
Prism.plugins.customClass.prefix('prism--')
// 2 
Prism.plugins.customClass.map({
	keyword: 'special-keyword',
	string: 'string_ch29s',
	comment: 'comment_93jsa'
})
// 3
import Prism from 'prismjs';
import classMap from 'styles/editor-class-map.css';
Prism.plugins.customClass.map(classMap)
```

I looked at the source for the component, and I don't think you provide a hook into the `plugins` of prism.js

**Comment by tomchentw** [comment]
Glad you find out! Feel free to suggest API changes for `react-prism`
