### ISSUE TITLE
Error: Prism is not defined

### ISSUE THREAD

**Issue by ulisessp** [tomchentw/react-prism#4]
i'm using version 1.2.1 and I'm getting the following error:

Uncaught ReferenceError: Prism is not defined PrismCode.js:29Uncaught Reference

Any ideas?

**Comment by tomchentw** [comment]
@ulisessp did you include `prism.min.js` in your html code?
https://github.com/tomchentw/react-prism/blob/a6a7f008355bfd62df4633872e2688f584fa8dd6/client/index.html#L7

**Comment by levitanong** [comment]
@tomchentw You might want to mention this in the readme. :)

But also, how are you able to src just prism.min.js? I don't find it on the same folder as in the client. :o

**Comment by tomchentw** [comment]
It's put under `/public` folder and get copied in the deployment script.
